### ISSUE TITLE
Query error on ubuntu AMI URL

### ISSUE THREAD

**Issue by brootware** [3ndG4me/Offensive-Security-Engineering-Udemy#2]
As mentioned earlier, in commit comment https://github.com/3ndG4me/Offensive-Security-Engineering-Udemy/commit/dfc881e9159e4097a787d6edbeb03cda9cc89af2#r88159094, when i tried to do `terraform plan` I'm getting an `Your query returned no results. Please change your search criteria and try again.`

So I changed the path back to the old value `ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*` and it seems to be working. Was this an accident while you were fixing the user and kali update? If so, I'd like to do a PR to this.

**Comment by 3ndG4me** [comment]
Hey @brootware this was not an issue that happened during the Kali update to my knowledge, but in unrelated testing I did notice I even had to update the query in my personal terraform scripts recently. If you'd like to submit a PR be my guest!
